import { readFileSync } from 'fs'
import { resolve } from 'path'
import puppeteer from 'puppeteer'

/**
 * Embed the UMU badge in PDF templates as base64 (FR-10.5).
 */
export function umuBadgeDataUri(): string {
  const svg = readFileSync(resolve(__dirname, '../../assets/umu-logo.svg'), 'utf-8')
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`
}

export interface PdfHeader {
  title: string
  facultyName: string
  reportDate: string
  periodLabel?: string
  subtitle?: string
}

export interface PdfTable {
  heading?: string
  headers: string[]
  rows: (string | number | null)[][]
}

/** Full HTML page with UMU header (university name, badge, faculty, date) + tables. */
export function buildPdfHtml(header: PdfHeader, tables: PdfTable[]): string {
  const badge = umuBadgeDataUri()
  const tableHtml = tables
    .map((t) => {
      const head = t.heading ? `<h3>${t.heading}</h3>` : ''
      const headerRow = `<tr>${t.headers.map((h) => `<th>${h}</th>`).join('')}</tr>`
      const bodyRows = t.rows
        .map((r) => `<tr>${r.map((c) => `<td>${c ?? ''}</td>`).join('')}</tr>`)
        .join('')
      const empty = t.rows.length === 0 ? '<tr><td colspan="100" class="empty">No data</td></tr>' : ''
      return `${head}<table><thead>${headerRow}</thead><tbody>${bodyRows}${empty}</tbody></table>`
    })
    .join('')

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    * { box-sizing: border-box; }
    body { font-family: Arial, Helvetica, sans-serif; color: #1a1a1a; font-size: 11px; margin: 0; }
    .header { display: flex; align-items: center; gap: 14px; border-bottom: 3px solid #CC0000; padding-bottom: 10px; }
    .header img { height: 70px; width: auto; }
    .header .title-block { flex: 1; }
    .header h1 { margin: 0; font-size: 20px; color: #CC0000; }
    .header .univ { margin: 0; font-size: 13px; font-weight: bold; }
    .header .meta { margin: 2px 0 0; font-size: 11px; color: #555; }
    h2 { color: #CC0000; font-size: 14px; margin: 14px 0 6px; }
    h3 { font-size: 12px; margin: 12px 0 4px; color: #333; }
    table { width: 100%; border-collapse: collapse; margin: 6px 0 14px; }
    th, td { border: 1px solid #ccc; padding: 5px 6px; text-align: left; }
    th { background: #F5C800; color: #333; font-size: 10px; text-transform: uppercase; }
    tr:nth-child(even) td { background: #fafafa; }
    .empty { text-align: center; color: #999; font-style: italic; }
    .footer { margin-top: 24px; font-size: 10px; color: #888; border-top: 1px solid #ddd; padding-top: 6px; }
    .pill { display: inline-block; padding: 1px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; }
    .good { background: #e7f6ec; color: #166534; }
    .warning { background: #fef3c7; color: #92400e; }
    .not-eligible { background: #fde8e8; color: #991b1b; }
    .none { background: #f1f5f9; color: #475569; }
  </style>
</head>
<body>
  <div class="header">
    <img src="${badge}" alt="UMU Badge">
    <div class="title-block">
      <p class="univ">Uganda Martyrs University</p>
      <p class="meta">Nkozi Campus · ${header.facultyName}</p>
      <h1>${header.title}</h1>
      <p class="meta">Report date: ${header.reportDate}${header.periodLabel ? ` · Period: ${header.periodLabel}` : ''}${header.subtitle ? ` · ${header.subtitle}` : ''}</p>
    </div>
  </div>
  ${tableHtml}
  <div class="footer">Generated by the UMU Attendance System · Uganda Martyrs University, Nkozi Campus</div>
</body>
</html>`
}

/** Render an HTML document to a PDF buffer via Puppeteer (FR-10). */
export async function renderPdf(html: string): Promise<Buffer> {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
  })
  try {
    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: 'load' })
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '18mm', bottom: '18mm', left: '14mm', right: '14mm' },
    })
    return Buffer.from(pdf)
  } finally {
    await browser.close()
  }
}

/** Build a full report PDF from header + tables in one call. */
export async function reportToPdf(header: PdfHeader, tables: PdfTable[]): Promise<Buffer> {
  return renderPdf(buildPdfHtml(header, tables))
}

/** Status pill cell (good / warning / not-eligible / none). */
export function statusPill(status: string): string {
  const cls =
    status === 'good' ? 'good' :
    status === 'warning' ? 'warning' :
    status === 'none' ? 'none' :
    'not-eligible'
  const label =
    status === 'good' ? 'Good' :
    status === 'warning' ? 'Warning' :
    status === 'none' ? 'No sessions' :
    'Not Eligible'
  return `<span class="pill ${cls}">${label}</span>`
}
